export interface KeywordMap {
  keyword: string;
  codes: number[];
}

export const SEVEN_CODE_KEYWORDS: KeywordMap[] = [
  { keyword: "공포", codes: [1] },
  { keyword: "배변 어려움", codes: [1] },
  { keyword: "하체 무거움", codes: [1] },
  { keyword: "통제", codes: [1, 3] },
  { keyword: "분노", codes: [1, 3] },
  { keyword: "식탐", codes: [1, 2] },
  { keyword: "활력 저하", codes: [1, 2] },
  { keyword: "방어적 자세", codes: [1, 2, 3] },
  { keyword: "골반 불편감", codes: [1, 2, 3] },
  { keyword: "불안", codes: [1, 2, 3] },
  { keyword: "미움", codes: [1, 3, 5] },
  { keyword: "지속적 피로", codes: [1, 3, 5] },
  { keyword: "책임감", codes: [1, 3, 5] },
  { keyword: "외로움", codes: [1, 2, 4] },
  { keyword: "관계 집착", codes: [1, 2, 4] },
  { keyword: "하복부 차가움", codes: [1, 2, 4] },
  { keyword: "돈 문제", codes: [2] },
  { keyword: "수치심", codes: [2] },
  { keyword: "아랫배 순환 저하", codes: [2] },
  { keyword: "감정적 피로", codes: [2, 4] },
  { keyword: "질투", codes: [2, 4] },
  { keyword: "답답함", codes: [2, 4, 6] },
  { keyword: "과도한 공감", codes: [2, 4, 6] },
  { keyword: "원망", codes: [2, 4, 6] },
  { keyword: "소화 더부룩함", codes: [3] },
  { keyword: "경쟁", codes: [3] },
  { keyword: "의욕저하", codes: [3] },
  { keyword: "권위적", codes: [3, 5] },
  { keyword: "억압", codes: [3, 5] },
  { keyword: "무기력", codes: [3, 5, 7] },
  { keyword: "열등감", codes: [3, 5, 7] },
  { keyword: "표현 어려움", codes: [3, 5, 7] },
  { keyword: "가슴 답답함", codes: [4] },
  { keyword: "가슴 뭉침", codes: [4] },
  { keyword: "상처", codes: [4] },
  { keyword: "냉소", codes: [4, 6] },
  { keyword: "오해", codes: [4, 6] },
  { keyword: "수면 불편", codes: [4, 6, 7] },
  { keyword: "비 현실감", codes: [4, 6, 7] },
  { keyword: "기분 저하", codes: [4, 6, 7] },
  { keyword: "수줍음", codes: [5] },
  { keyword: "목소리 불편감", codes: [5] },
  { keyword: "목 뻣뻣함", codes: [5] },
  { keyword: "혼란", codes: [5, 7] },
  { keyword: "무지", codes: [5, 7] },
  { keyword: "머리 무거움", codes: [5, 6, 7] },
  { keyword: "정보 과부하", codes: [5, 6, 7] },
  { keyword: "긴장", codes: [5, 6, 7] },
  { keyword: "시각 피로", codes: [6] },
  { keyword: "예민함", codes: [6] },
  { keyword: "집중력 부족", codes: [6] },
  { keyword: "창의성 부재", codes: [6, 7] },
  { keyword: "혼돈", codes: [6, 7] },
  { keyword: "단절감", codes: [7] },
  { keyword: "존재감 상실", codes: [7] },
  { keyword: "기력 약화", codes: [7] },
];
