// 7코드 점검에 필요한 56가지 에너지/심신 상태 키워드 및 점수 매핑 데이터 정의 파일
export interface KeywordMap {
  keyword: string;
  keywordEn: string;
  codes: number[];
}

export const SEVEN_CODE_KEYWORDS: KeywordMap[] = [
  { keyword: "공포", keywordEn: "Fear", codes: [1] },
  { keyword: "배변 어려움", keywordEn: "Bowel Discomfort", codes: [1] },
  { keyword: "하체 무거움", keywordEn: "Heavy Lower Body", codes: [1] },
  { keyword: "통제", keywordEn: "Control Issues", codes: [1, 3] },
  { keyword: "분노", keywordEn: "Anger", codes: [1, 3] },
  { keyword: "식탐", keywordEn: "Food Cravings", codes: [1, 2] },
  { keyword: "활력 저하", keywordEn: "Low Vitality", codes: [1, 2] },
  { keyword: "방어적 자세", keywordEn: "Defensive Posture", codes: [1, 2, 3] },
  { keyword: "골반 불편감", keywordEn: "Pelvic Discomfort", codes: [1, 2, 3] },
  { keyword: "불안", keywordEn: "Anxiety", codes: [1, 2, 3] },
  { keyword: "미움", keywordEn: "Resentment", codes: [1, 3, 5] },
  { keyword: "지속적 피로", keywordEn: "Chronic Fatigue", codes: [1, 3, 5] },
  { keyword: "책임감", keywordEn: "Heavy Responsibility", codes: [1, 3, 5] },
  { keyword: "외로움", keywordEn: "Loneliness", codes: [1, 2, 4] },
  { keyword: "관계 집착", keywordEn: "Relationship Clinging", codes: [1, 2, 4] },
  { keyword: "하복부 차가움", keywordEn: "Cold Lower Abdomen", codes: [1, 2, 4] },
  { keyword: "경제 문제", keywordEn: "Financial Stress", codes: [2] },
  { keyword: "수치심", keywordEn: "Shame / Guilt", codes: [2] },
  { keyword: "아랫배 순환 저하", keywordEn: "Poor Abdominal Circulation", codes: [2] },
  { keyword: "감정적 피로", keywordEn: "Emotional Exhaustion", codes: [2, 4] },
  { keyword: "질투", keywordEn: "Jealousy", codes: [2, 4] },
  { keyword: "답답함", keywordEn: "Frustration", codes: [2, 4, 6] },
  { keyword: "과도한 공감", keywordEn: "Excessive Empathy", codes: [2, 4, 6] },
  { keyword: "원망", keywordEn: "Grudge / Blaming", codes: [2, 4, 6] },
  { keyword: "소화 더부룩함", keywordEn: "Bloating / Indigestion", codes: [3] },
  { keyword: "경쟁", keywordEn: "Competitiveness", codes: [3] },
  { keyword: "의욕저하", keywordEn: "Lack of Motivation", codes: [3] },
  { keyword: "권위적", keywordEn: "Authoritative Attitude", codes: [3, 5] },
  { keyword: "억압", keywordEn: "Suppression", codes: [3, 5] },
  { keyword: "무기력", keywordEn: "Lethargy / Helplessness", codes: [3, 5, 7] },
  { keyword: "열등감", keywordEn: "Inferiority Complex", codes: [3, 5, 7] },
  { keyword: "표현 어려움", keywordEn: "Difficulty Expressing", codes: [3, 5, 7] },
  { keyword: "가슴 답답함", keywordEn: "Chest Tightness", codes: [4] },
  { keyword: "가슴 뭉침", keywordEn: "Chest Discomfort", codes: [4] },
  { keyword: "상처", keywordEn: "Emotional Hurt", codes: [4] },
  { keyword: "냉소", keywordEn: "Cynicism", codes: [4, 6] },
  { keyword: "오해", keywordEn: "Misunderstandings", codes: [4, 6] },
  { keyword: "수면 불편", keywordEn: "Sleep Disturbances", codes: [4, 6, 7] },
  { keyword: "비 현실감", keywordEn: "Derealization", codes: [4, 6, 7] },
  { keyword: "기분 저하", keywordEn: "Low Mood / Gloom", codes: [4, 6, 7] },
  { keyword: "수줍음", keywordEn: "Shyness", codes: [5] },
  { keyword: "목소리 불편감", keywordEn: "Voice Strain", codes: [5] },
  { keyword: "목 뻣뻣함", keywordEn: "Stiff Neck / Throat", codes: [5] },
  { keyword: "혼란", keywordEn: "Confusion", codes: [5, 7] },
  { keyword: "무지", keywordEn: "Ignorance / Unawareness", codes: [5, 7] },
  { keyword: "머리 무거움", keywordEn: "Heavy Head", codes: [5, 6, 7] },
  { keyword: "정보 과부하", keywordEn: "Information Overload", codes: [5, 6, 7] },
  { keyword: "긴장", keywordEn: "Tension / Tightness", codes: [5, 6, 7] },
  { keyword: "시각 피로", keywordEn: "Eye Strain", codes: [6] },
  { keyword: "예민함", keywordEn: "Hypersensitivity", codes: [6] },
  { keyword: "집중력 부족", keywordEn: "Lack of Focus", codes: [6] },
  { keyword: "창의성 부재", keywordEn: "Block in Creativity", codes: [6, 7] },
  { keyword: "혼돈", keywordEn: "Disorientation", codes: [6, 7] },
  { keyword: "단절감", keywordEn: "Sense of Isolation", codes: [7] },
  { keyword: "존재감 상실", keywordEn: "Loss of Presence", codes: [7] },
  { keyword: "기력 약화", keywordEn: "Weakened Vital Energy", codes: [7] },
];
